#ifndef CONFIG_CLIENT_H
#define CONFIG_CLIENT_H

#define TS_PORT 10000
#define DELIMITER ';'
#define PORT_UDP_ECHO 9100
#define PORT_UDP_TIME 9200
#define PORT_TCP_ECHO 9300
#define PORT_TCP_TIME 9400
#define UDP_ECHO_SERVICE 1
#define UDP_TIME_SERVICE 2

#endif